### ISSUE TITLE
More fine-grained packages for texlive

### ISSUE THREAD

**Issue by jakobjakobson13** [flathub/org.freedesktop.Sdk.Extension.texlive#35]
As we use the texlive install with a `texlive.profile` file, we could split up this package into the collections

```
collection-basic
collection-bibtexextra
collection-binextra
collection-context
collection-fontsextra
collection-fontsrecommended
collection-fontutils
collection-formatsextra
collection-games
collection-humanities
collection-langarabic
collection-langchinese
collection-langcjk
collection-langcyrillic
collection-langczechslovak
collection-langenglish
collection-langeuropean
collection-langfrench
collection-langgerman
collection-langgreek
collection-langitalian
collection-langjapanese
collection-langkorean
collection-langother
collection-langpolish
collection-langportuguese
collection-langspanish
collection-latex
collection-latexextra
collection-latexrecommended
collection-luatex
collection-mathscience
collection-metapost
collection-music
collection-pictures
collection-plaingeneric
collection-pstricks
collection-publishers
collection-texworks
collection-xetex
```
that are defined within the texlive installer resulting in 42 texlive "subpackages" following for example this naming scheme `org.freedesktop.Sdk.Extension.texlive.collection-basic` or similar. If tex editors include them as optional addons this could  decrease the installation size for the users and gives them for fine control over the packages they need.

In the `texlive.profile` files the following two lines are needed for the respective changes:
```
selected_scheme scheme-custom
collection-basic 1  # or for example collection-music 1
```
.

**Comment by jakobjakobson13** [comment]
The minimal package for all editors should include the `scheme-medium` as this includes the most important packages
```
scheme-medium
=============
longdesc This is the medium TeX Live collection: it contains plain TeX,
longdesc LaTeX, many recommended packages, and support for most European
longdesc languages.
depend collection-basic
depend collection-binextra
depend collection-context
depend collection-fontsrecommended
depend collection-fontutils
depend collection-langczechslovak
depend collection-langenglish
depend collection-langeuropean
depend collection-langfrench
depend collection-langgerman
depend collection-langitalian
depend collection-langpolish
depend collection-langportuguese
depend collection-langspanish
depend collection-latex
depend collection-latexrecommended
depend collection-luatex
depend collection-mathscience
depend collection-metapost
depend collection-plaingeneric
depend collection-texworks
depend collection-xetex
```
for most users. This leaves the collections 
```
collection-bibtexextra
collection-fontsextra
collection-formatsextra
collection-games
collection-humanities
collection-langarabic
collection-langchinese
collection-langcjk
collection-langcyrillic
collection-langgreek
collection-langjapanese
collection-langkorean
collection-langother
collection-latexextra
collection-music
collection-pictures
collection-pstricks
collection-publishers
```
to package.

**Comment by jakobjakobson13** [comment]
Would you favour such a reorganisation @stloeffler and @dgcampea?

**Comment by jakobjakobson13** [comment]
The resulting manifests (or dependencies) could be adapted similar to [https://github.com/flathub/org.shotcut.Shotcut](https://github.com/flathub/org.shotcut.Shotcut) where a `org.freedesktop.Sdk.Extension.texlive.base` could be defined similar to [https://github.com/flathub/org.freedesktop.LinuxAudio.BaseExtension](https://github.com/flathub/org.freedesktop.LinuxAudio.BaseExtension) with its plugins `org.freedesktop.Sdk.Extension.texlive.mediumscheme` or `org.freedesktop.Sdk.Extension.texlive.bibtexextra`.

**Comment by stloeffler** [comment]
I think I am generally in favor of such a restructuring, although I have too little experience with flatpak to understand all the details...
What I can explain, of course, is the idea behind TeXworks and its packaging. At its core, TeXworks is a text editor that can call other (external) programs. It's intended for these to be TeX & friends, but they can really by anything (including e.g., make and other build systems). As such, TeXworks itself is a fairly small binary (a few 10s of MB). Building it does not require TeX to be installed at all.
From what I could tell so far, the sandboxing approach taken by flatpak (and other, similar packaging systems) essentially requires all external programs an app calls to be bundled with the app. If there is any way around bundling about 1 GB of TeX with a 10ish MB program, I'm all for it. Moreover, I am very much in favor of not bundling (separate "installations") of TeX with each editor, so that the user only has to download the TeX distro once and can then swap editors in and out. Additionally, I think it's a good idea if users could pick what part of TeX & friends (e.g., collections) they need, rather than having to download everything in the off chance that there is some user out there that requires musical typesetting, unusual fonts, crossword creation, and all math packages at the same time ;).

What I am wondering about: why should this be an Sdk extension? As far as TeXworks is concerned, it's not required for building, just for running the program as intended. But then again, I'm not at all well-versed in flatpak extensions.

**Comment by jakobjakobson13** [comment]
> I think I am generally in favor of such a restructuring, although I have too little experience with flatpak to understand all the details...

Well, me too actually.

> From what I could tell so far, the sandboxing approach taken by flatpak (and other, similar packaging systems) essentially requires all external programs an app calls to be bundled with the app. If there is any way around bundling about 1 GB of TeX with a 10ish MB program, I'm all for it. Moreover, I am very much in favor of not bundling (separate "installations") of TeX with each editor, so that the user only has to download the TeX distro once and can then swap editors in and out. Additionally, I think it's a good idea if users could pick what part of TeX & friends (e.g., collections) they need, rather than having to download everything in the off chance that there is some user out there that requires musical typesetting, unusual fonts, crossword creation, and all math packages at the same time ;).

I could point texworks to a local tex (`~/texlive/bin/x86_64`) installation but not to a global (`usr/bin`) with the first one as a possible solution. However, I think in modern days, people should be offered a graphical tex installation via their package manager and this leads to the more granular approach.
 
> What I am wondering about: why should this be an Sdk extension? As far as TeXworks is concerned, it's not required for building, just for running the program as intended. But then again, I'm not at all well-versed in flatpak extensions.

That was done before my time to save maintainers some work by just adding a few lines to each build manifest compared to adding the "complete" texlive manifest to each build manifest.

**Comment by jakobjakobson13** [comment]
I'll close this issue for now.
